### ISSUE TITLE
EMAIL VERIFICATION

### ISSUE THREAD

**Issue by ph4t0o0o0om** [AjinkyaBijwe/VideoWEBRTC#2]
Hi Good day. Badly need your help. I'm waiting the email verification sent to me because I register new user but it takes too long until now i can't receive the emai. Any help please? Thank you so much!!!

**Comment by AjinkyaBijwe** [comment]
![image](https://user-images.githubusercontent.com/8812357/43794378-1476f536-9a4c-11e8-9fa2-ef4340d1ad91.png)

Add your username and password in line 67-68 in cofig.php to enable verification

**Comment by cahn75** [comment]
hello can you u help me about the login. it was ok i can register and verify email but after i visit the site to login... dont let me in?but the password and username was correct just it stop me to login and put me back to login form can u tell me whats the problem of ur site

**Comment by vihangmi10** [comment]
Hi sorry for the delay I will have to check if the site is live on. Or if there is some problem with the database that is causing that issue. I will get back as soon as I have an answer
